language: python


python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

#addons:
    #apt:
        #packages:
#            - graphviz
#            - texlive-latex-extra
#            - dvipng

env:
    matrix:
        - SETUP_CMD='test'

matrix:
    include:

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        #- python: 2.7
        #  env: SETUP_CMD='build_sphinx -w'

    exclude:

        #- python: 3.3
        #  env: SETUP_CMD='test'
          
install:
    - pip install -U pip
    - pip install twine
    - for i in $(ls -d */); do cd $i; pip install -r dev_requirements.txt; cd ..; done
    - pip install coveralls

script:
    - for i in $(ls -d */); do cd $i; pytest --cov $i || exit 1; cd ..; done

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    # Run coverage for all Python versions but submit only once - 3.5
    - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then coverage combine $(ls -d */.coverage) || exit 1; coveralls; fi

jobs:
  include:
    - stage: publish
      python: 3.4
      deploy:
         provider: script
         script: ./.publish.sh
         on:
            tags: true
            condition: ${PYPI_PASSWORD+x} = x
            branch: master
