name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  egginfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tox
        run: python -m pip install --upgrade tox
      - name: egg-info
        run: tox -e egg_info

  tests_mac_windows:
    needs: egginfo
    runs-on: ${{ matrix.os }}
    needs: tests
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install tox
      run: python -m pip install --upgrade tox
    - name: tests
      run: tox


  style_coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install tox
        run: python -m pip install --upgrade tox
      - name: Check codestyle
        run: tox -e codestyle
      - name: Check coverage
        run: tox -e cov
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
       
  #publish:
  #needs: coverage
  #TODO - should be trigger by tagging associated with creating a new release in
  # github. The tag should be compared to the version in setup.cfg to ensure
  # consistency.



